### ISSUE TITLE
Request to maintain the project

### ISSUE THREAD

**Issue by jasonm23** [jxa/pivotal-tracker#18]
Hi Jxa

I'd like to take over this project now that you're no longer using Pivotal Tracker.

I also work for Pivotal Labs now, so it would be a nice fit for me to look after this.

Let me know what you think.

Thank you

**Comment by jxa** [comment]
@jasonm23 Thank you for offering to take over. It's true I haven't been using Pivotal Tracker in my current job. I'm happy to have the help.

**Comment by jasonm23** [comment]
Up to you how you'd like to do this.

We can move the project to another org, or you can add me as a owner, collaborator etc.

I'm flexible.

**Comment by jxa** [comment]
After thinking about it some more, I think we should just start with the normal PR process. I shouldn't be too much of a blocker, and if it turns out that I'm getting in the way I'll add you as collaborator. After I've merged a couple of your PRs I'll add you as a collaborator.

Please don't take offense. I just would like to take it a bit slower, and I do retain an interest in the project

**Comment by jasonm23** [comment]
No problem.

just here to help.

I'll fix the missing key bindings / commands first. 

 I'll look at bigger stories later on.

**Comment by jxa** [comment]
Great!
